### ISSUE TITLE
[BUG]  Unable to install due to unsigned release

### ISSUE THREAD

**Issue by juneflowers** [hwittenborn/makedeb#10]
Hi I wanted to try out this awesome project but I'm unable to install after following the setup instructions due to the repository not being signed.

```
W: GPG error: https://proget.hunterwittenborn.com makedeb Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7AAC098FF084C445
E: The repository 'https://proget.hunterwittenborn.com makedeb Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by hwittenborn** [comment]
Hi!

Could you try running the GPG step (the `wget -qO -` one) in the docs again?

If it still fails, try running the `wget` command by itself, and see what it outputs.

The file at `/usr/share/keyrings/makedeb-archive-keyring.gpg` might also have some info. If it doesn't look like gibberish, it might help as well.

**Comment by juneflowers** [comment]
Just ran it, it works! Thanks. Installed just fine now.

**Comment by hwittenborn** [comment]
Great! Glad to hear it's all checking out.
