### ISSUE TITLE
makedeb ignores all arguments

### ISSUE THREAD

**Issue by nawordar** [hwittenborn/makedeb#101]
### Issue

Regardless of what I type, `makedeb` always makes a package. I can't provide version information using `makedeb --version`, because well, it also makes a package. `makedeb-makepkg` works fine, although it prints a warning, that it is supposed to be used internally.

I am running `makedeb` on a freshly updated Arch Linux, installed from AUR. Here is the `/usr/bin/makedeb` from my system: [makedeb].

### Installation source

Arch User Repository (AUR)

### Installed release type

Stable

### Installed makedeb version

8.7.1-1, according to `makedeb_package_version` in `/usr/bin/makedeb`

### Installed makepkg version

8.7.1-1

[makedeb]: https://github.com/makedeb/makedeb/files/7877296/makedeb.txt

**Comment by hwittenborn** [comment]
I noticed the issue the other day, and I'm pretty sure I know the culprit. I'll let you know once I get a fix in.

**Comment by hwittenborn** [comment]
Should be fixed now @nawordar. I'll have it deployed to beta and stable within 30 minutes.
