### ISSUE TITLE
Respect backup key in PKGBUILD

### ISSUE THREAD

**Issue by nightah** [hwittenborn/makedeb#107]
### Description of feature

Files output by makedeb do not respect the `backup` key, therefore files that should be protected from being overwritten during installation are not.

If makedeb could generate [conffiles](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles) based on the `backup` key this would resolve this issue.

### Installed makedeb version

8.7.1-1

**Comment by hwittenborn** [comment]
Just so I can confirm on how you'd like this implemented:

So you'd want something like this in the PKGBUILD:

```sh
# Maintainer: Foo Bar <foobar@example.org>
pkgname=test-pkg
pkgver=1.0.0
pkgrel=1
pkgdesc='Test package'
arch=('any')
backup=('/etc/conffile' '/etc/conffile2')
```

With the following conffile generated:

```
/etc/conffile
/etc/conffile2
```

**Comment by james-d-elliott** [comment]
I believe that's correct. I tried to manually generate it but did not get much success, I suspect because it was creating the file in the package content area not in the debian metadata dir.

The file may need to be debian/conffiles inside the deb itself, I'm not entirely sure. A package installed via it should cause dpkg to generate a file named `/var/lib/dpkg/info/<pkg name>.conffiles` if it's done correctly.

**Comment by hwittenborn** [comment]
Thanks for that file reference @james-d-elliott, I didn't know how that worked before now :)

Yeah, I think the file needs to be placed at `pkg/{pkgname}/DEBIAN/` in regards to makedeb's packages, though I'll figure that all out when I test locally.

**Comment by james-d-elliott** [comment]
If you need help feel free to ping me. As long as the file gets generated on the host as I described it should be fine. It is however improper to have the package manually install that file, dpkg is meant to install it from that meta dir.

I can also provide an example .deb made with debuild if that helps.

**Comment by hwittenborn** [comment]
How critical is this for y'all? Looking at your [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=authelia#n21), it looks like you're just backing up a file under the `/etc` directory, which the Debian docs say are already flagged as conffiles.

**Comment by hwittenborn** [comment]
I'm not trying to avoid implementing this, I'm just a bit busy with rewriting the UI for the MPR at the moment, and I'm wondering how much of a priority this would be if it would already be covered by dpkg and all that already.

**Comment by james-d-elliott** [comment]
Can you point to docs that indicate that dpkg does that? We've had users report this is not the case and I can adequately replicate it  even when installing the same deb which would indicate this is not accurate.

The only docs I can find on it being automatic are when it's a package built with debhelper specifically dh_installdeb, and the `/var/lib/dpkg/info/<pkg name>.conffiles` file still exists in those instances, it does not exist then dpkg doesn't automatically handle this as far as I can tell.

**Comment by hwittenborn** [comment]
Just looked at the docs again, and it's saying that it only happens when using `dh_installdeb`. Must've overlooked it while reading it.

It definitely looks like support for this is still needed then.

**Comment by hwittenborn** [comment]
There is this one issue I noticed though -

Debian wants a full pathname for conffiles that starts with a `/`, while makepkg wants that omitted. Would it be too much of a pain to maintain some kind of PKGBUILD where the `backup` key starts with the `/`, or just have the PKGBUILD generated somehow with it added?

**Comment by hwittenborn** [comment]
Everything should be ready to go in that PR as long as we can get that above issue figured out.

I'd like to force having the `/` at the beginning when using makedeb, as I don't think it'd be wise to auto-add it otherwise, and I don't think forcing it to be omitted would be best either since the conffiles spec says otherwise.

**Comment by james-d-elliott** [comment]
I'm not entirely sure about the conventions regarding PKGBUILD, so I'll have to ask @nightah. On face value it seems a little strange that's how you'd handle it, but it's possible I'm overthinking it.

**Comment by hwittenborn** [comment]
@james-d-elliott: Would you guys be open in the Authelia support rooms rn? If it's possible on your guys' end I'd like to just knock this out now. If that doesn't work that's fine too

**Comment by james-d-elliott** [comment]
I am personally free, don't think @nightah  is around.

**Comment by hwittenborn** [comment]
This should be deployed into stable in a few minutes if you guys want to start using the feature in your packaging.

**Comment by nightah** [comment]
Confirmed it works a treat. Thanks @hwittenborn.
