### ISSUE TITLE
Add universal installation script to install makedeb on any Debian or Arch Linux based distribution

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/makedeb#113]
### Description of feature

Current direction seems to be that we're gonna be making the makedeb ecosystem more user friendly for newbies, so we should probably create an installation script that can be used to install makedeb from Debian, Ubuntu, Arch Linux, or any of their derivatives. Likewise, we'd probably just put something like this in the README for using the script once we finish it:

```sh
curl -Ls 'https://shlink.makedeb.org/install' | bash -
```

This would just use the Shlink instance I have hosted at https://shlink.hunterwittenborn.com, and just have it at shlink.makedeb.org for branding purposes.

We also might add an example for Wget usage, though afaik curl is gonna be more likely to be installed on most Linux distributions, and having an example for both curl and Wget might be overcomplicated for newbies (maybe?), and I don't see much of a benefit if I can assure curl's gonna be installed on most systems (probably just desktop; server users are probably not gonna be bombarded by newbies).

### Installed makedeb version

N/A

**Comment by lpuv** [comment]
[instl](https://docs.instl.sh/#/) could also be an option.

**Comment by hwittenborn** [comment]
Has since been added to the README as well as the [homepage](https://makedeb.org).
