### ISSUE TITLE
support ‍`:‍‍‍‍‍`?

### ISSUE THREAD

**Issue by mobin-2008** [hwittenborn/makedeb#118]
### Issue

Hello. I noticed that a 32-bit package could not be installed due to a problem (possibly a bug?).

Because makedeb does not seem to support ':'

This is part of my PKGBUILD:
```
depends=(
desktop-file-utils
desktop-file-utils:i386
```
I need ':' to install 32-bit packages!

Is there a solution?

### Installation source

APT Repository

### Installed release type

Beta

### Installed makedeb version

makedeb 9.0.3-1

### Installed makepkg version

-

**Comment by mobin-2008** [comment]
This is an error that occurs:
`[!] depends contains invalid characters: ':'`

**Comment by hiddeninthesand** [comment]
Related to #27 and #75

**Comment by hwittenborn** [comment]
Sorry, I completely forgot about this and didn't get around to looking into it.

I didn't quite know how the architecture specifiers worked here before, but I'm seeing how they should be used now, and I see how they're necessary in some situations.

I'll let you know when something's implemented.

**Comment by mobin-2008** [comment]
> Sorry, I completely forgot about this and didn't get around to looking into it.
> 
> I didn't quite know how the architecture specifiers worked here before, but I'm seeing how they should be used now, and I see how they're necessary in some situations.
> 
> I'll let you know when something's implemented.

thanks

**Comment by mobin-2008** [comment]
Please add this issue to 'Better Debian Integration' milestone

**Comment by hwittenborn** [comment]
You're right, needs to be there. Added

**Comment by hwittenborn** [comment]
@mobin-2008: Do you know what fields `:` characters can be used on? I've tried looking up documentation on it but I've come out empty handed. I know I can always just try each field manually and find out, but finding a defined spec would definitely be preferred.

**Comment by mobin-2008** [comment]
> @mobin-2008: Do you know what fields `:` characters can be used on? I've tried looking up documentation on it but I've come out empty handed. I know I can always just try each field manually and find out, but finding a defined spec would definitely be preferred.

I'm not very good at using apt/dpkg but I know that with the `:` character you can get a package for a specific architecture (already added repositories).
For example:
`sudo apt install faudio:i386`
or:
`sudo apt install faudio:amd64`

I have never seen any other use for it.

**Comment by hwittenborn** [comment]
Thanks @mobin-2008! I'll do some testing on my end to figure out the specifics to everything, and there should (hopefully) be something implemented soon. I'm working on some MPR stuff atm, but I plan on working on this right after that.
