### ISSUE TITLE
Vision and RoadMap

### ISSUE THREAD

**Issue by Aeres-u99** [hwittenborn/makedeb#120]
### Description of feature

Summarizing the discussion from Makedeb General: 

Currently with github projects we are tracking the 
+ Bug reports
+ Feature requests 
But certainly we do not still have something which tracks:
+ Our vision 
+ Our future plans 
+ Road map
+ Something which tracks multiple lines of development and future of currently existing projects
For example we are not sure on what else needs to be implemented, even if we are sure (like hunter has been planning to rev up the UI for makedeb and work on their cohesion), we need something where we can track the priorities, the handlers, TUs and the required responsibilities, Documentations and a a lot of things. 

Having something like focalboard and updating things to track the priority and projects would be greatly helpful. Also, along with that inclusion of separate projects ideas such as `makedeb-termux` would be an amazing insertion (and a lots of tracking and work as well) 

Kindly pitch in your opinions with this regard.

### Installed makedeb version

makedeb 8.7.0-1

**Comment by hwittenborn** [comment]
I was just thinking about this, and I think some things could definitely be done, like documentation could be improved. I think that'd make an excellent choice for part of a roadmap, so I'm definitely now +1 on making one. I'll try to get one going soon.

**Comment by hwittenborn** [comment]
> Our vision

That's to simplify the lives for people packaging for Debian based systems :). I'd care to argue that's plastered pretty much everywhere.

> - Our future plans
> - Road map
> - Something which tracks multiple lines of development and future of currently existing projects

See https://github.com/orgs/makedeb/projects/6. I've also made a milestone for [Debian integration](https://github.com/makedeb/makedeb/milestone/1). Let me know if there's anything else you'd like added, I'm still open to adding some more.
