### ISSUE TITLE
Move all code to `src/makepkg/` codebase.

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/makedeb#130]
We currently have two separate parts of code, `src/makedeb/` and `src/makepkg/`, with the former being our code, and the latter being of makepkg.

We should try to get everything into a single codebase, instead of maintaining two separate ones that make it harder to maintain.

**Comment by hiddeninthesand** [comment]
Shouldn't all code be moved to `src/makedeb/` instead of `src/makepkg/`?

**Comment by hwittenborn** [comment]
I mostly meant we'll be using the makepkg codebase at some point - we'll move all files to `src/` instead of a subfolder afterwards.
