### ISSUE TITLE
Allow to set `DEBIAN_FRONTEND=noninteractive` when installing package dependencies

### ISSUE THREAD

**Issue by soenkehahn** [hwittenborn/makedeb#131]
### Description of feature

Some packages on ubuntu by default ask some interactive questions during installation, e.g. what timezone the user's in (package `tzdata`) or what keyboard layout they want to use (package `keyboard-configuration`). Normally this can be avoided by setting the environment variable `DEBIAN_FRONTEND` to `noninteractive`. But that doesn't seem to work when `makedeb` is installing packages.

Is there any way to avoid the interactive step during the package installation?

Here's the `PKGBUILD` file that reproduces the problem:
```
pkgname=test-package
pkgver=0.0.0
pkgrel=1
pkgdesc='test package'
arch=('any')
depends=(
  'keyboard-configuration'
)

package() {
  true
}
```

When I run `makedeb -si` on this file on a system where `keyboard-configuration` isn't yet installed, `makedeb` tries to install it and the installation will ask interactive questions. Setting `DEBIAN_FRONTEND` to `noninteractive` doesn't change that.

This is on ubuntu:21.04.

### Installed makedeb version

commit 804e3c564c3aafea505a9ecf308d4beedd6797f6 installed from source

**Comment by hwittenborn** [comment]
Closed in [v14.1.1](https://github.com/makedeb/makedeb/releases/tag/v14.1.1-stable) via the `--pass-env` flag.
