### ISSUE TITLE
updpkgsums command

### ISSUE THREAD

**Issue by d-513** [hwittenborn/makedeb#132]
### Description of feature

On arch, the `pacman-contrib` package contains a utility `updpkgsums`, which updates the checksums of packages.
It would be nice to have this functionality in makedeb

### Installed makedeb version

11.0.1-1

**Comment by hwittenborn** [comment]
Since this is in a separate package on Arch Linux, I'd also prefer if it was such regarding makedeb.

Would creating an MPR package or such on your end work?

**Comment by d-513** [comment]
yes, this would work

**Comment by hwittenborn** [comment]
Closing this for now since it seems like the consensus was to make this a separate package.
