### ISSUE TITLE
Show error when `pkgname=pacstall`

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/makedeb#134]
### Description of feature

It looks like Pacstall is going to be doing the same for makedeb, so we should do the same for the giggles.

We should allow building with that pkgname by passing a super long flag that makes it really inconvenient to use. I'm thinking upwards of 100 characters, though maybe more if we deem it to be necessary. 

### Installed makedeb version

N/A

**Comment by wizard-28** [comment]
# Sus

![sus](https://i0.wp.com/pbs.twimg.com/media/EsmjTcNVkAA_bar.png)

**Comment by hwittenborn** [comment]
Test comment, plz ignore

**Comment by Elsie19** [comment]
Any updates?

**Comment by hwittenborn** [comment]
I was gonna wait until Pacstall added the feature too - what are you wanting to do?

**Comment by Elsie19** [comment]
> I was gonna wait until Pacstall added the feature too - what are you wanting to do?

That's gonna take a while though. 2.0.0 isn't gonna be out for many many months

**Comment by hwittenborn** [comment]
I think it'd be best to wait until Pacstall is also ready to deploy this too, just due to the nature of the change. There's a lot of potential for negativity with it, and I think both projects need to be doing it around the same time to avoid risking that.

**Comment by d-513** [comment]
sus

**Comment by Elsie19** [comment]
> sus

sussy wussy

**Comment by Elsie19** [comment]
The sussy saga has ended!
