### ISSUE TITLE
[BUG] Dependency installation broken in Debian 10 (buster)

### ISSUE THREAD

**Issue by leadpogrommer** [hwittenborn/makedeb#15]
Debian buster has old apt version which does not support `satisfy` command

**Comment by hwittenborn** [comment]
This is an issue that's been frequently brought up inside of makedeb's support rooms on Matrix.

I'd like to add a `depends=('apt>=version')` version to the PKGBUILD, but I'm not exactly sure what version the `satisfy` command came into effect.

**Comment by emanuelserpa** [comment]
> This is an issue that's been frequently brought up inside of makedeb's support rooms on Matrix.
> 
> I'd like to add a `depends=('apt>=version')` version to the PKGBUILD, but I'm not exactly sure what version the `satisfy` command came into effect.

apt 1.9

Source: https://ubunlog.com/en/apt-satisfy-new-command-that-will-arrive-in-eoan-ermine-together-with-apt-1-9-from-debian/

**Comment by hwittenborn** [comment]
I'll do some confirming on my end, and make the changes if everything checks out.

I also might change the way the dependency checker works to not even use the `satisfy` command. The new system I'm thinking of would work like this:

1. Generate a dummy package only containing the control file, which would contain all build dependencies under `depends`.

2. Install the dummy package with `apt-get install ./packagename.deb`.

3. Once the build is complete, simply remove the dummy package.

There could be some issues that pop up (such as with conflicting package names), but I don't think any of it would be *unsolvable*.

**Comment by hwittenborn** [comment]
I'm pretty sure this is solved now as makedeb isn't using the `satisfy` command to check dependencies anymore.

Feel free to reopen if the issue still remains though.

**Comment by Menci** [comment]
https://github.com/makedeb/makedeb/blob/65549cf6c1dcf71f655f2f49e9f4c30286aab8f5/src/main.sh#L1374

It's using `apt-get satisfy` here.

**Comment by hwittenborn** [comment]
@Menci: Due to some changes in makedeb, it's now pretty much forced that we have to use `apt-get` satisfy now.

I probably need to look into what minimum apt version we need to use as a result of that though, I'll do that after I finish some other stuff, which might be a hot minute. Feel free to open a PR if you'd want that done more urgently though.

If you have any ideas into avoiding using `satisfy`, I'm down with looking into that too.
