### ISSUE TITLE
Failed to parse git revision string

### ISSUE THREAD

**Issue by jonascant** [hwittenborn/makedeb#171]
I am currently trying to write a PKGBUILD for a music player called strawberry.

When i run makedeb 14.1.1- I get the following error:
`[#] Starting build()...
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
CMake Error at cmake/Version.cmake:74 (message):
  Failed to parse git revision string 'e1ce81c'
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)`

What does this mean?
Thanks!

**Comment by hwittenborn** [comment]
Could you send over the PKGBUILD you're using?

**Comment by jonascant** [comment]
Sure, this is it (still a work in progress):

pkgname=strawberry-git
provides=('strawbery')
conflicts=('strawberry')
pkgdesc="A music player aimed at audio enthusiasts and music collectors"
pkgver=1.0
pkgrel=1
arch=(amd64 i686 arm armv6h armv7h aarch64)
url="https://www.strawberrymusicplayer.org/"
license=("GPL3")
depends=(
    'libchromaprint1'
    'libprotobuf-dev'
    #'libgstreamer-plugins-bad1.0-dev'
    'libgstreamer-plugins-base1.0-0'
    'qtbase5-dev'
    'sqlite3'
    'udisks2'
    'dbus'
    'libdssialsacompat-dev' #alsa-lib
    'libcdio-dev'
    'fftw-dev'
    'libpulse-dev'
    #'libimobiledevice-dev'
    #'libplist-dev'
    #'libusbmuxd-dev'
    #'libgpod-dev'
    #'libmtp-dev'
)

makedepends=(
	'git'
	'cmake'
	'libboost-dev'
	'qtbase5-dev-tools'
	'libgtest-dev'
	'libgmock-dev'
)


source=("git+https://github.com/jonaski/strawberry.git")
sha256sums=('SKIP')

prepare() {
  cd "${pkgname%-git}"
  install -d strawberry-build
}

build() {
  cd "${pkgname%-git}/strawberry-build"
  cmake .. \
    -DBUILD_WITH_QT5=ON

  make
}

package() {
    cd ${srcdir}/${pkgname}-${pkgver}
    make DESTDIR=${pkgdir} install

    # remove conflict with ctags package
    #mv ${pkgdir}/usr/bin/{ctags,ctags.emacs}
    #mv ${pkgdir}/usr/share/man/man1/{ctags.1.gz,ctags.emacs.1}

    ## fix user/root permissions on usr/share files
    #find ${pkgdir}/usr/share/emacs/${pkgver} -exec chown root:root {} \;
}

Sorry about the formatting.

**Comment by hwittenborn** [comment]
Does building the package without using makedeb work?

**Comment by hwittenborn** [comment]
Closing since there hasn't been any response. Feel free to reopen if you got any updates.
