### ISSUE TITLE
Makedeb install failing to install the final deb file built

### ISSUE THREAD

**Issue by justvipul** [hwittenborn/makedeb#19]
a problem with Makedeb
https://termbin.com/5s4t
Check out the last line. It's not detecting the full name of the deb file after this run if I run 
sudo apt install ./filename.deb
It works as it should

**Comment by hwittenborn** [comment]
Everything should be good to now. If it still keeps not working, feel free to reopen the issue.

**Comment by justvipul** [comment]
the problem persits.
im on bullseye so apt version is not a problem.
here is the error for fzf-git if i run with makedeb-alpha version as `makedeb -si` 
https://termbin.com/x5p7
however if i install the deb file manually later on it works as it should.
https://termbin.com/3rk2

**Comment by hwittenborn** [comment]
You're on the stable release then, correct?

If I'm not mistaken, this issue should be fixed inside of the alpha and beta releases. If I can confirm that it's at least only happening in the stable release, I can issue a patch to fix the issue real quick.

**Comment by justvipul** [comment]
> You're on the stable release then, correct?
> 
> If I'm not mistaken, this issue should be fixed inside of the alpha and beta releases. If I can confirm that it's at least only happening in the stable release, I can issue a patch to fix the issue real quick.

As I mentioned I tried it in alpha. The pkgbuild cannot complete with stable branch so can't test on it

**Comment by hwittenborn** [comment]
Didn't expect it to close it automatically :/

Anyway, let me know if you still have any issues.

**Comment by justvipul** [comment]
No issues now. Everything working great.
