### ISSUE TITLE
check_deps: command not found

### ISSUE THREAD

**Issue by Thelta** [hwittenborn/makedeb#196]
### Issue

I have been porting a PKGBUILD and it gave me `/usr/share/makedeb/executable/vcs.sh: line 81: check_deps: command not found` error. ~~This error didn't happen on 14.1.2~~. This happens on default docker image. Here is the current PKGBUILD. 

``` PKGBUILD
# Maintainer: Bruno Pagani <archange@archlinux.org>

pkgname=libyuv
pkgver=2322+3aebf69d
pkgrel=1
pkgdesc="Library for YUV scaling"
arch=(amd64)
url="https://chromium.googlesource.com/libyuv/libyuv/"
license=(custom)
depends=('libjpeg-turbo8')
makedepends=('cmake' 'git' 'libjpeg-turbo8-dev' 'ninja-build')
# Version required by libavif
_commit=966768e899c0eb932e1cd72935d37e15284daec0
source=(git+${url})
sha512sums=('SKIP')

pkgver() {
  cd ${pkgname}
  printf "%s+%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

prepare() {
  cd ${pkgname}
  git checkout ${_commit}
  sed -i 's|yuvconvert ${JPEG_LIBRARY}|${ly_lib_shared} ${JPEG_LIBRARY}|' CMakeLists.txt
}

build() {
  cmake -B build -S ${pkgname} \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -GNinja
  cmake --build ./build
}

package() {
  DESTDIR="${pkgdir}" cmake --install
  install -Dm644 ${pkgname}/LICENSE -t "${pkgdir}"/usr/share/licenses/${pkgname}/
}


```

### Installation source

APT Repository 

### Installed release type

Alpha

### Installed makedeb version

15.0.1

**Comment by Thelta** [comment]
Well, fixed it after installing git. It seems it tries to clone the repository before installing the makedepends.

**Comment by hwittenborn** [comment]
It definitely shouldn't be doing that, I'll be at my computer a bit later and I'll look into it then.

**Comment by hwittenborn** [comment]
It looks like it's issue when trying to verify if VCS packages are installed; it appears to be happening right after the linting phase but before sources are actually cloned.

makepkg in Arch Linux appears to be calling this function but also doesn't seem to have it defined, I guess some of my changes just made this pop up, but I couldn't reproduce with makepkg strangely.
