### ISSUE TITLE
[BUG] package version mismatch & so no .deb package created

### ISSUE THREAD

**Issue by realmazharhussain** [hwittenborn/makedeb#20]
I use makepkg to create a package for my Manjaro installation from my [git repo](https://github.com/realmazharhussain/easier-linux). It runs perfectly and creates a {pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst package which can be installed without any problem. But when I run makedeb on it, it fails with the output given below

```
==> Making package: easier-linux-git 5.97f054b-1 (Fri Jul 30 11:39:36 PKT 2021)...
==> Converting architecure...
==> Entering fakeroot environment...
==> Running makepkg...
==> Retrieving sources...
==> Extracting sources...
==> Starting pkgver()...
==> Starting package()...
target DESTDIR dirctory = /home/mazhar/gitapps/easier-linux/pkg/easier-linux-git
created dirctory /home/mazhar/gitapps/easier-linux/pkg/easier-linux-git/etc/skel
target home dirctory = /home/mazhar/gitapps/easier-linux/pkg/easier-linux-git/etc/skel

installing user files ...
installing system-wide files ...
installing gEdit files ...
installing debian/ubuntu files ...
installing c++ files ...
installing ffmpeg files ...
installing wine files ...
installing youtube-dl files ...
installing fish files ...

done.
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "easier-linux-git"...
  -> Compressing package...
tar: easier-linux-git-unknown.unknown-1-any.pkg.tar.zst: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

The last two lines of output are indications of an issue. For some reason, it is trying to find package with version unknown.unknown when it actually created an ArchLinux package with version ${number}.${commitID}.

## How to reproduce the issue?

```bash
git clone https://github.com/realmazharhussain/easier-linux
cd easier-linux
makedeb
```

## Expected Behavior

makedeb should run successfully like makepkg does

## What actually happens?

makedeb fails trying to convert ${package}.pkg.tar.zst into a .deb package because it gets its name(version part of it) wrong.

**Comment by hwittenborn** [comment]
Could I ask what release of makedeb you're using (alpha, beta, or stable)?

**Comment by realmazharhussain** [comment]
Oh... Sorry! I should have mentioned that in my first comment in the issue.

I have tried all three of the following from the AUR and all of them have this same problem.

- **makedeb-stable**: 5.9.5-1
- **makedeb-beta**: 5.11.5-1
- **makedeb-alpha**: 5.11.5-1

**Comment by hwittenborn** [comment]
Hmm, that's a bit weird.

Could you try running `makedeb --verbose` (followed by any options you'd normally use) and post the output to a pastebin or something similar?

The issue you're getting should only be able to happen in some older versions of makedeb if you're on the alpha or stable release. Though I'm not doubting I'm wrong, in which case the logs from the above output should help me figure out the issue.

**Comment by realmazharhussain** [comment]
**Command**: makedeb --verbose
**PWD**: (git)realmazharhussain/easier-linux
**MakeDeb Version**: 5.11.5 (alpha)
**MakePKG Version**: 6.0.0
**Output**: https://pastebin.com/yisS0vrS

**Comment by hwittenborn** [comment]
This should now be fixed in the `makedeb-alpha` package. I'll leave this open until everything migrates to stable.

**Comment by realmazharhussain** [comment]
Thanks

**Comment by hwittenborn** [comment]
Everything should be deployed to stable now. Feel free to reopen if the issue still persists.
