### ISSUE TITLE
Question: How can I make a DKMS package?

### ISSUE THREAD

**Issue by Menci** [hwittenborn/makedeb#203]
I tried to build [a DKMS package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=netfilter-fullconenat-dkms-git) with `makedeb`, but after installing the `deb` file, `dkms` won't install the module automatically.

**Comment by hwittenborn** [comment]
I honestly haven't even heard of DKMS until now, I wouldn't really know. Maybe this [Ubuntu wiki](https://help.ubuntu.com/community/DKMS) article could help?

This isn't much of a question on makedeb functionality though, things like packaging help should be left to the support rooms. Feel free to ask again in there if you need more help though :)

**Comment by Menci** [comment]
I tested and found that I just need to use `postinst` and `prerm` scripts:

```bash
package() {
  # ...

  # Add postinst and prerm scripts
  postinst="src/postinst"
  prerm="src/prerm"
  echo "dkms install ${pkgname}/${pkgver}" > "${srcdir}/postinst"
  echo "dkms remove ${pkgname}/${pkgver}" > "${srcdir}/prerm"
}
```
