### ISSUE TITLE
[BUG] makedeb-alpha and makedeb-beta should conflict with and provide makedeb but don't

### ISSUE THREAD

**Issue by realmazharhussain** [hwittenborn/makedeb#21]
## Problems

1. When switching among different versions/branches of makedeb using the AUR, I noticed, I manually have to remove/uninstall one version/branch of makedeb before installing the other or it won't install.
2. If any other package depends on makedeb, It would need to install makedeb(stable) even if makedeb-alpha or makedeb-beta is installed. And if makedeb-alpha or makedeb-beta is already installed, it would prevent dependent package from installation because of Problem#1.

## Fix

Following two lines should be added to PKGBUILDs of `makedeb-alpha` and `makedeb-beta`

```bash
provides=('makedeb')
conflicts=('makedeb')
```

So that installing one version/branch of makedeb would automatically remove/uninstall any other version/branch if it was already installed and makedeb-alpha and makedeb-beta can satisfy the dependency of makedeb if any package requires it.

**Comment by hwittenborn** [comment]
I remember noticing that the [PKGBUILDs for the AUR](https://github.com/makedeb/makedeb/tree/alpha/PKGBUILDs/AUR) didn't haven't the proper packages in `conflicts` a bit back, and I just kind of forgot about it.

Anyway, I'll get the issue fixed right after I get https://github.com/makedeb/makedeb/issues/20 solved.

**Comment by realmazharhussain** [comment]
OK

Thanks

**Comment by realmazharhussain** [comment]
`makedeb-alpha` and `makedeb-beta` still don't provide `makedeb`. So, only half the issue is solved. Please reread `Problem #2`.

`makedeb-alpha` and `makedeb-beta` not providing `makedeb` also creates another problematic scenario that I forgot to mention in the first comment; When some other third-party package conflicts with `makedeb`, it will only conflict with `makedeb-stable` and that will cause problems for the user when either `makedeb-alpha` or `makedeb-beta` is installed on the system instead of `makedeb-stable`.

The best solution to all these problems that I can see is `makedeb-alpha` and `makedeb-beta` having the following two arrays be exactly the same as below in their `PKGBUILD`s

```bash
provides=('makedeb')
conflicts=('makedeb')
```

And `PKGBUILD` of `makedeb-stable` not having these arrays at all.

This is how package conflicts are officially managed in Arch Linux and Debian.

**Comment by hwittenborn** [comment]
Everything should be deployed to stable now. Feel free to reopen if the issue still persists.
