### ISSUE TITLE
Dotfile found in package root

### ISSUE THREAD

**Issue by knokelmaat** [hwittenborn/makedeb#231]
### Issue

When trying to install a package (`una-bin`) from MPR using `makedeb -si`, the installation fails with the following error message:
`[!] Dotfile found in package root '/home/christophe/Downloads/una-bin/pkg/una-bin/.*'` This is on Debian Unstable distribution.

### Installation source

Apt

### Installed release type

Alpha

### Installed makedeb version

6.0.0-alpha5

**Comment by knokelmaat** [comment]
Seems like this is a duplicate of #73. I also see that there is already a PR pending ( #229 ).

**Comment by hwittenborn** [comment]
This is a duplicate, yeah. Feel free to comment or upvote the other issue, I'll try to get that MR merged shortly though.
