### ISSUE TITLE
Add a working installation process in README.md

### ISSUE THREAD

**Issue by Popolon** [hwittenborn/makedeb#248]
### Issue

If the README.md installation if followed from a non root user, the password is asked, and this end with

<pre>[!] The script was ran in noninteractive mode, but no makedeb package was specified to install.
[!] Please specify a package to install via the 'MAKEDEB_RELEASE' environment variable.</pre>

Without any clue.. 

After following the docs link (would be simpler if it is already in the README.md) . The same thing is given here, but there is a clue for usage after the recommendation: https://docs.makedeb.org/installing/shell-script/

So you could simply add th toe README.md:

Set the MAKEDEB variable as is (why for defining a MAKEDEB variable in makedeb project for building makedeb?) and launch the command:

<pre>export MAKEDEB_RELEASE='makedeb'
bash -c "$(wget -qO - 'https://shlink.makedeb.org/install')"</pre>

It would simplify greatly the new coming people usage.

### Installation source

makedeb Package Repository (MPR)

### Installed release type

Stable

### Installed makedeb version

all

**Comment by hwittenborn** [comment]
Hmm, that popup should only be showing when running in a noninteractive environment, I can confirm it's not behaving that way though.

It probably does need to list what packages to choose from too, I'll get both of those fixed real quick.

**Comment by hwittenborn** [comment]
Fixed in https://github.com/makedeb/makedeb/commit/edb3606f1a791bae7b2e4198fbdf8b65b0a1613d.
