### ISSUE TITLE
Support dash on pkgver

### ISSUE THREAD

**Issue by Heus-Sueh** [hwittenborn/makedeb#251]
### Description of feature

![image](https://user-images.githubusercontent.com/98482469/214946189-03a2a830-8903-4667-b4ef-ae9469b2ec06.png)
![image](https://user-images.githubusercontent.com/98482469/214946126-482b6e14-de3a-4b58-bd4e-4fc481c16a03.png)

### Installed makedeb version

makedeb 6.0.0-stable Stable Release

**Comment by hwittenborn** [comment]
With makedeb you'd use `pkgrel` for such:

```sh
pkgver=109.0
pkgrel=1
```

That error message probably needs improved now that you mention this though. I'll try to get that done sometime soon, though I'm fairly busy with a side project that'll probably keep me busy for the next month or so, though it may be less if I can get it done sooner.
