### ISSUE TITLE
pkgver() is evaluated before the source is fetched

### ISSUE THREAD

**Issue by DrMcCoy** [hwittenborn/makedeb#26]
### Issue

The pkgver() function is evaluated before the source is fetched (from a git:// source, in this case). This means it fails and doesn't update the pkgver variable correctly. On Arch, that process works as intended.

[This here is the (gzip'd) PKGBUILD in question](https://github.com/makedeb/makedeb/files/6986969/PKGBUILD.gz), which is basically just a slightly modified version of https://github.com/xoreos/xoreos-tools/blob/master/dists/arch/PKGBUILD

(package() also still fails with this PKGBUILD, not yet sure why. It's currently still unmodified from the AUR PKGBUILD, so I guess it doesn't work like that for MPR.)

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

5.9.5

### Installed makepkg version

6.0.0

**Comment by hwittenborn** [comment]
makedeb is **supposed** to ignore those errors when they happen, but I've already got a system in place (think it's just on alpha and beta atm) where it doesn't even need to run `pkgver()` directly, and just gets the package version from build metadata after makepkg runs.

While the system is in place, I think I still have remnants of the `pkgver()` stuff running, which I'm assuming is causing the issues.

Point being: Issue's confirmed on my end, and I'll try to have a fix implemented soon.

**Comment by hwittenborn** [comment]
Regarding your `package()` error: It looks like it's an error with the `make` command itself.

The `package()` function isn't handled directly by makedeb, and is run by makepkg during build time, so there shouldn't be too many points of failure where makedeb could've caused an issue.

**Comment by DrMcCoy** [comment]
> makedeb is **supposed** to ignore those errors when they happen

I mean, yes, the build continues, but the version information is wrong. Because this is a package build from the git master branch, I need some way to put some version number in there. Which, in Arch, is done with the pkgver() function, from what I understand, so that's what I did there.

> but I've already got a system in place (think it's just on alpha and beta atm) where it doesn't even need to run `pkgver()` directly, and just gets the package version from build metadata after makepkg runs

That would of course also do it, yeah. :)

I guess until then, I guess I'll only do a release-version PKGBUILD, not a rolling git one. That doesn't need to update the pkgver.

> Regarding your `package()` error: It looks like it's an error with the `make` command itself.

Which is weird, it's just a make install, and that target is generated by the autotools. There's really nothing manual I'm doing there. It tries to install a file called "0", which doesn't exist. I haven't really investigated it further, though.

**Comment by hwittenborn** [comment]
> The build continues, but the version information is wrong.

Are you talking about the `Making package: pkgname ...` stuff? Getting the output that makedeb is giving you directly would help clarify everything as well.

> It tries to install a file called "0", which doesn't exist.

Yeah, all sounds like something with the Makefile (or whatever make uses) itself.

If you could point me to where the build file is, I might be able to confirm that makedeb isn't behaving incorrectly though.

**Comment by DrMcCoy** [comment]
Ah, yes, I found the problem: you're overriding the environment variable ```$INSTALL```: https://github.com/makedeb/makedeb/blob/alpha/src/makedeb.sh#L24

Since you're ```export```'ing it into subshells, this is also set when the autoconf-generated ```configure``` script is called. For ```configure```, this variable has a special role: if set, it's taken as an alternative to use for ```/usr/bin/install``` (other similar variables exist: ```CC```, ```LD```, etc., basically for all individual toolchain parts), i.e. the command that's called from ```make install``` to do the actual installing (i.e. copying, setting permissions, etc.) of the target files.

**Comment by hwittenborn** [comment]
Guess that explains it :P

I'm just wrapping up a rewrite for makedeb's dependency processing, and then I'll get that fixed.

**Comment by DrMcCoy** [comment]
Likewise, https://github.com/makedeb/makedeb/blob/alpha/src/makedeb.sh#L43 explains why the autogen.sh script I provide (which basically just does autoreconf with the required flags) fails, and I had to explicitly call autoreconf instead in build().

Because the one I provide actually uses srcdir if that's set for the directory the source is in (where the configure.ac file is). Granted, that's not *standard* as such, but I've seen other projects do that. I'm actually not sure anymore what the intended usecase is :P

**Comment by hwittenborn** [comment]
That issue's just rooted in the original `pkgver()` issue, right? Or is it something else?

**Comment by DrMcCoy** [comment]
No, no, autogen.sh is called in build(). It's a wrapper script that calls autoreconf with the required flags, which runs through the autotools steps (libtoolize, autoconf, automake) to generated the configure script. It's a vital step of the build system.

Really, If you're ```export```ing shell variables (if you even really need to ```export``` them in the first place!), you should probably prefix them with something, like ```MAKEDEB_```, so that they don't clash with anything any build system might use.

**Comment by hwittenborn** [comment]
Yeah, most of the variables at the top of the script don't need to be exported.

You'll find a lot of stuff that's being exported throughout the script (in the stable branch anyway), such as `depends`, `optdepends`, and probably a ton of other things.

It was mostly just from poor coding on my part, but the beta and alpha releases are in the midst of cleaning all that up. I still need to do some more cleanup, but it's getting a lot better than it was previously.

There's currently a far bit of changes that are awaiting migration to stable (see all the open issues with the `solved` tag) - they were originally awaiting a bug with built packages where APT would print a warning about a size issue when reinstalling a package with the same version (i.e. `pkgname 1.0` is installed, and you're trying to reinstall `pkgname` with that same version). As of a few days ago, I've decided it's quite a minor bug though, so I just plan on shipping it to stable for the time being.

The only reason there isn't an open issue for it as well is that I haven't had time to reconfirm it on my machine, so it's kind of just been sitting in my brain (I'd also like to add a note in the source code assuming I don't forget). Regardless, all these fixes should hopefully be in stable soon after I get all the needed testing done.

I'll also just change those variables to be prefixed with `MAKEDEB_` or something too. Can't really see any downsides to it, so why not :man_shrugging:

**Comment by hwittenborn** [comment]
Everything should be deployed to stable now. Feel free to reopen if the issue still persists.
