### ISSUE TITLE
Support the pipe character for declaring dependencies

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/makedeb#27]
### Description of feature

Debian supports the use of the following format for declaring dependencies:

```package, package1 | package2, package3```

In this case, it would require the following packages to be installed:

- `package`
- `package1` **or** `package2`
- `package3`

It would be nice if makedeb could support this as well, perhaps with something like this:

```sh
depends=("package" "package1|package2" "package3")
```

### Installed makedeb version

5.16.2

**Comment by Elsie19** [comment]
How would makedeb determine which package to install, and would there be a way to automatically pick one, which would be useful for hands free building/installing.

**Comment by hwittenborn** [comment]
The same way APT and such does, which I believe is as follows:

If any package in the list of packages is already installed, it uses that. Otherwise, it defaults to the first one in the list that can be found in the package cache.
