### ISSUE TITLE
Installer script not found...

### ISSUE THREAD

**Issue by ByerRA** [hwittenborn/makedeb#272]
### Issue

When I execute the following to install "makedeb" per the directions...

`bash -ci "$(wget -qO - 'https://shlink.makedeb.org/install')"`

Nothing happens.  If I do the following...

`wget https://shlink/makedeb.org/install`

I get the following error...

`--2023-06-28 11:10:57--  https://shlink.makedeb.org/install
Resolving shlink.makedeb.org (shlink.makedeb.org)... 104.237.134.92
Connecting to shlink.makedeb.org (shlink.makedeb.org)|104.237.134.92|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-28 11:10:57 ERROR 404: Not Found.
`

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

None

**Comment by hwittenborn** [comment]
Looks like there was a misconfigured setting in makedeb's DNS records. I've had to migrate a bunch of servers recently, and it looks like this got caught up in all of that.

It should all be fixed now, but feel free to send a message if it's still not working.
