### ISSUE TITLE
A colon gets added in the deb files name and which results in the rejection of Deb file

### ISSUE THREAD

**Issue by justvipul** [hwittenborn/makedeb#29]
### Issue

I'm using Makedeb-beta
And trying to install fzf-git
Everything goes fine until it reaches the Install part of the deb file. And as the deb file has a colon added the deb file name had illegal characters and thus gets unrecognised
Here's an ls after building the deb file successfully
https://ezup.dev/p/lgj72i

### Installation source

APT Repository

### Installed release type

Beta

### Installed makedeb version

6.3.1

### Installed makepkg version

8.5.0

**Comment by hwittenborn** [comment]
(If you didn't know already) That colon is used to denote the `epoch` variable from a PKGBUILD, which your package appears to contain.

Regardless, that character shouldn't be in the built package's name, as building with standard Debian tools never seems to keep it in either.
