### ISSUE TITLE
while upgrading packages via packages or manually following error occurs. (makedeb -si OR tap upgrade)

### ISSUE THREAD

**Issue by justvipul** [hwittenborn/makedeb#33]
### Issue

when running makedeb -si or using tap as tap upgrade gives the following error when the installing process of the final deb file is about to finish. heres how it looks if done via `tap upgrade`
![image](https://i.imgur.com/RO51K9d.png)

### Installation source

APT Repository

### Installed release type

Beta

### Installed makedeb version

6.3.4-1

### Installed makepkg version

8.5.0-1

**Comment by hwittenborn** [comment]
See [this thread](https://groups.google.com/g/linux.debian.devel/c/IQZ7f-eYXrA?pli=1) from the debian-devel mailing list, which provides some information on why the error should disappear in newer releases of APT.

There's obviously something missing from makedeb about size information in built packages which I need to figure out, but as long as the issue's gonna be gone from APT, it's really not a big priority for me to find and implement a solution atm.

**Comment by hwittenborn** [comment]
Closing this due to the aformentioned comment. If this becomes a big enough issue, let me know and I'll look into it more.
