### ISSUE TITLE
Add Transifix page for makedeb translations

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/makedeb#36]
We should start creating translations for makedeb, as there are already users using makedeb that don't use English as there primary language, and it would thus be better for them if makedeb could also be in their native languages.

**Comment by hwittenborn** [comment]
Looks like if we use [Weblate](https://weblate.org/en/) we can selfhost, so we'll probably end up just using that.

**Comment by hwittenborn** [comment]
[Accent](https://github.com/mirego/accent) also appears that it would work for our purposes, and has a bit better of a UI imo.

**Comment by hwittenborn** [comment]
Looks like we're gonna use Weblate. It doesn't have the best UI for my personal tastes, but it looks like it's gonna have the most functionality for what it's gonna be used for, and it seems to be the most popular, helping us to ensure that it remains supported by the upstream.

**Comment by hwittenborn** [comment]
I decided to settle on Weblate. The makedeb translation page can be found at https://weblate.makedeb.org/projects/makedeb/makedeb.

**Comment by maboroshin** [comment]
Weblate for makedeb is not available and the issue should be re-open. Pinned if necessary.

The [po folder](https://github.com/makedeb/makedeb/tree/alpha/po) contains the original ```.pot``` file. This ```.pot``` file can be read by PoEditor or other software to auto-convert to the target language file. Contributors can also translate manually in this way.

If you change to this method, the following documents need to be changed. In any case, the reference to the non-existent weblate should be removed.

* [CONTRIBUTING.md](https://github.com/makedeb/makedeb/blob/alpha/CONTRIBUTING.md)
* [ways-to-support-makedeb.md](https://github.com/makedeb/makedeb-docs/blob/main/content/support/ways-to-support-makedeb.md)

----
* [News: Announcing Translation Support for makedeb](https://www.makedeb.org/news/announcing-translation-support-for-makedeb/) (Apr 25 2022)

**Comment by maboroshin** [comment]
@hwittenborn : If translators pull requests a translation file, will it be merged?

**Comment by hwittenborn** [comment]
Thanks for the notice @maboroshin. makedeb's Weblate instance was dropped a while ago as part of a migration to hosted.weblate.org, but I must've overlooked migrating makedeb's translations to there as part of that process.

I haven't had a ton of time to work on makedeb as of recent - I've been quite busy with other projects I've worked on, and it's been hard to fit time for makedeb inside of that. I likewise can't guarantee when your PR would get looked at if you were to make one either. It's not the way I'm wanting it to work, but I haven't been able to do much else currently.

I'm looking for maintainers to help keep makedeb moving forward, but I haven't found too many people yet. Until I can find some people I can't guarantee how much progress will be made in anything related to makedeb.

If you want to make an issue about makedeb's translation website being down I'd be fine with pinning it though.

**Comment by maboroshin** [comment]
Thanks for the reply. I understand the situation.

When you have time, the migration to hosted.weblate.org is complete. Then we can translate from weblate.

Also you may have less time to merge pull requests.
