### ISSUE TITLE
Add a way to specify install scripts using separate folder or variables

### ISSUE THREAD

**Issue by zocker-160** [hwittenborn/makedeb#38]
### Description of feature

When packaging a program which offers a DEB file, then currently it is not very convenient to specify the install scripts, which are already present in the downloaded DEB file.

It would be great to be able to just extract the `controls.tar.gz` into a special folder or have special variables, which contain a path to the script file.

### Installed makedeb version

6.3.11-1

**Comment by hwittenborn** [comment]
Related: #41

**Comment by hwittenborn** [comment]
Would something like this not work?

```sh
prepare() {
  tar -gz control.tar.gz -C control/
}

package() {
  postinst="${srcdir}/control/postinst"
}
```

And so on for other types of installation scripts.

**Comment by zocker-160** [comment]
@hwittenborn That would work, but I also think that this issue becomes more or less irrelevant if you implement #88 .

**Comment by hwittenborn** [comment]
Superseded by #88.
