### ISSUE TITLE
Incorrectly handle custom functions in `.install` scripts

### ISSUE THREAD

**Issue by uqsme** [hwittenborn/makedeb#41]
### Intro

When a AUR package contains a `.install` script, it seems `makedeb` only convert four standard functions to the Debian `postinst` script:
https://github.com/makedeb/makedeb/blob/5eaca07bc2acd929b215aef877ebe41cfd713d24/src/functions/add_install_scripts.sh#L9-L22
However, some `.install` scripts try to call custom functions in the installation process. In the case of [`chromium-snapshot-bin`](https://aur.archlinux.org/pkgbase/chromium-snapshot-bin/), custom `note()` function (shown below) isn't properly treated and causes the failure of configure.
```bash
# Colored makepkg-like functions
msg_blue() {
    printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note "Pepper Flash is now auto-detected from: /usr/lib/PepperFlash/ (AUR/pepper-flash)"
    note "Custom flags should be put directly in: ~/.config/chromium-flags.conf"
    note "The launcher is called: 'chromium-snapshot-bin'"
}


post_upgrade() {
    post_install
}
```

### Reproduce
```bash
$ git clone https://aur.archlinux.org/chromium-snapshot-bin.git/
$ cd chromium-snapshot-bin
$ kate PKGBUILD # change deps and pkgver
$ makedeb
$ dpkg -i chromium-snapshot-bin_9x.x.xxxx.x.xxxxx.deb # install successfully, but fail to configure
```

### Sys Info
Debian bullseye + KDE Plasma 5.20
HP pavilion sleekbook 14

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

6.3.11-1

### Installed makepkg version

8.5.2-1

**Comment by hwittenborn** [comment]
This was something that was brought up in makedeb's support rooms over on Matrix, and it's 99% probably going to require the .install scripts to be deprecated in favor of the separate files that Debian packages use (those being `postinst`, `preinst`, `postrm`, and `prerm`).

The current plan is to use something like this as the alternative to .install files:

```sh
pkgname=foobar
pkgver=1
pkgrel=2
arch=('any')

postinst="path/to/postinst/script"
preinst="path/to/preinst/script"
```

And etc etc.

This also gives the benefit of allowing the script to be written in a language other than Bash, though it'll mean that, in regard to your example, the relevant functions will have to be copied manually to each file.

It's probably not the most ideal, but it's definitely gonna be the best for integration with Debian packaging considering that's what's used natively.

**Comment by hwittenborn** [comment]
Opening until all the changes migrate to the stable branch
