### ISSUE TITLE
Fetching and Installation of distro specific dependencies is broken

### ISSUE THREAD

**Issue by zocker-160** [hwittenborn/makedeb#48]
### Issue

this screenshot should contain all the relevant information

![grafik](https://user-images.githubusercontent.com/36563538/137788403-ec3de5e8-3097-4865-8c04-ee0bcf21006d.png)

changing to
```
focal_depends
bullseye_depends
```
or changing the order does not fix the issue

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

7.1.2-1

### Installed makepkg version

8.8.0-1

**Comment by hwittenborn** [comment]
Issue's [right here](https://github.com/makedeb/makedeb/blob/stable/src/functions/dependency_checks/check_distro_dependencies.sh#L17-L19) due to the misnamed variable string.

I'll get that fixed up real quick.

**Comment by hwittenborn** [comment]
The changes should be deployed to the APT repository right now, but it looks like the AUR and MPR deployments are failing right now.

Unless it poses to be a big issue I'll just leave it as so until I just get `alpha` merged into `stable` which should fix up deployment issues, which should in turn be merged over within the next week or so.
