### ISSUE TITLE
additional packages having install script get rejected by dpkg in the install stage.

### ISSUE THREAD

**Issue by justvipul** [hwittenborn/makedeb#50]
### Issue

1. install fzf-tab-completion, then nerd-font-victor-mono or any nerd font. does not matter.
2. then try installing ntfd.
heres the error that comes up while installing the deb starts. https://ezup.dev/p/ptqcys

### Installation source

APT Repository

### Installed release type

Beta

### Installed makedeb version

8.1.0-1

### Installed makepkg version

8.10.1-1

**Comment by hwittenborn** [comment]
Should be fixed, but this is one of the few times I've had to patch the stable release to fix the issue, so it may not work properly there (though my local testing is working out fine).

You'll need to rebuild any packages that own any of the following files (you can find out which by running `dpkg -S file`, replacing `file` with any of the below files):

```
/.PREINST
/.POSTINST
/.PRERM
/.POSTRM
```

Feel free to reopen if the issue persists.
