### ISSUE TITLE
Add Installed-Size to control file (in control.tar.gz)

### ISSUE THREAD

**Issue by vifly** [hwittenborn/makedeb#52]
### Description of feature

Usually the control file (in control.tar.gz) of deb package being built will have the field Installed-Size, which can tell the user how much storage space the package will take up. For example,

```
# After decompress deb package
$ tar -xf control.tar.xz
$ rg Installed-Size
control
5:Installed-Size: 37
```
If no Installed-Size, when using apt to install package, it will say the package will take up 0KB of storage space, which is ridiculous.

Please add Installed-Size to the control file of deb package being built.

### Installed makedeb version

makedeb (7.1.2+bugfix1-1) - Stable Release

**Comment by vifly** [comment]
I tested makedeb v8.3.0-1-alpha, it works.

**Comment by hwittenborn** [comment]
Great!

I'll actually keep the issue open until the feature gets merged into stable so you know when you can start using it there.
