### ISSUE TITLE
makedeb --version shows incorrect values when built with native debian packaging

### ISSUE THREAD

**Issue by lpuv** [hwittenborn/makedeb#56]
When running `makedeb --version`:
```
﻿makedeb (8.3.3-1) - Stable Release
makepkg (8.3.3-1)
```

8.3.3-1 is the latest alpha version, not stable. This might be rooted in other issues, because it seems that the `--version` command pulls the version from other functions.

**Comment by hwittenborn** [comment]
Before going further can I ask what release you're on?

**Comment by lpuv** [comment]
I am on alpha, gotten via the PPA/native debian packaging.

**Comment by hwittenborn** [comment]
Ok, that makes sense then.

The release type is set to stable for the Debian packages, regardless of what branch it builds from. The release type is a user defined value at build time, so it's not necessarily going to match if it isn't set correspondingly.

See https://github.com/makedeb/makedeb/blob/alpha/Makefile#L68-L71 for the instructions used for the Debian package.
