### ISSUE TITLE
Suggests using `-f` to overwrite, but option `-f` is not accepted

### ISSUE THREAD

**Issue by maxpoulin64** [hwittenborn/makedeb#59]
### Issue

When a package is already built, makedeb claims the package is already built and suggests using the `-f` option:

```
[!] Part of the package group has already been built. (use -f to overwrite)
```

However, `-f` is not a valid option to makedeb:

```
ubuntu@builder:~/my-package$ makedeb -f
[!] Unknown option '-f'
```

Clearly this option is meant to be passed through to makepkg, but I haven't found a way to specify options for makepkg within makedeb.

### Installation source

APT Repository

### Installed release type

Beta

### Installed makedeb version

8.3.1-1

### Installed makepkg version

8.12.1-1

**Comment by hwittenborn** [comment]
This should only really happen if a build while in makepkg fails, though from your other issue I'm seeing that in turn revealed this one.

I'll probably just spend some time on making makepkg not generate any archive at all (the `.pkg.tar.gz` in the directory on a failed build). I need to get some other things done though such as getting some much needed changes into stable, so for the time being I'd just delete the archive on failed runs (though from what I understand it won't be an issue anyway after I get that other one fixed up, which should take less time to fix as I already found the origin of the issue anyway).

**Comment by hwittenborn** [comment]
Currently fixed in the `alpha` release.
