### ISSUE TITLE
[!] pkgver 'r1636.71a6ef6' is not allowed to start with a digit.

### ISSUE THREAD

**Issue by SoftwareRat** [hwittenborn/makedeb#63]
### Issue

Hello,
i tried to install my own moonlight-qt-git from [here](https://aur.archlinux.org/packages/moonlight-qt-git), but with creating the deb file i get this error message:
`"[!] pkgver 'r1636.71a6ef6' is not allowed to start with a digit."`

Is there any workarrund for this?

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

7.1.2+bugfix3-1

### Installed makepkg version

8.8.0-1

**Comment by hwittenborn** [comment]
Looks like I made a typo when making the checks on the string set for pkgver, but it should be reading that it *should* start with a number.

Just remove the `r` prefix and if should be fine.

**Comment by giomf** [comment]
Got a question about that!

Why should pkgver only start with digits?
With makepkg this is allowed, I think it makes sense to comply with the following [guideline](https://wiki.archlinux.org/title/VCS_package_guidelines#The_pkgver()_function).

Why did you decide against it? How should we cover a case where the upstream repo has no tag?
Edit: You could add a zero as addressed in the guideline. But I think it would be better without.

**Comment by hwittenborn** [comment]
@Giom-fm See https://www.debian.org/doc/debian-policy/ch-controlfields.html#version under `upstream_version`.

This is a requirement for Debian packages, and since makedeb is building those it needs to comply with that format, which may or may not differ from that on Arch Linux sometimes.

**Comment by giomf** [comment]
Ok i see.
I will do it like this then.

Thanks!

**Comment by hwittenborn** [comment]
Looks like this issue got resolved. Feel free to send a message here or open a new issue if you're still experiencing problems.
