### ISSUE TITLE
makedeb not working correctly on debian 11

### ISSUE THREAD

**Issue by oevcim** [hwittenborn/makedeb#64]
### Issue

makedeb command giving error

makedeb: row 137: trap: sigint: invalid signal declaration

makedeb version: 7.1.2+bugfix3-1

### Installation source

APT Repository

### Installed release type

Stable

### Installed makedeb version

7.1.2+bugfix3-1

### Installed makepkg version

8.8.0-1

**Comment by oevcim** [comment]
makedeb-alpha (8.4.6-1) also gives the same error with row number 158.

**Comment by hwittenborn** [comment]
I can't reproduce on my end:

![image](https://user-images.githubusercontent.com/74838472/144765298-503dec33-5a29-4335-9b20-c5bf075eab97.png)

Could you send the full output of makedeb on your machine?

**Comment by oevcim** [comment]
![makedeb_error](https://user-images.githubusercontent.com/61584685/144794913-4728b42a-5b60-40b5-86fd-56c14f2a58b3.png)

I am facing with this. I have installed via apt repository. What are the possible reasons?

**Comment by hwittenborn** [comment]
Hmm, that is a bit weird. Regarding reasons I'm kind of clueless :P

It's a bit of a last resort, but could you run the following and paste the output to a pastebin? It'll let me see exactly what code is inside the `makedeb` executable on your machine:

```sh
cat /usr/bin/makedeb
```

**Comment by oevcim** [comment]
It is the [output](https://zerobin.net/?692e7915ca349c42#0d9vF38hQhjiPQalvvjo49QKEzZxj+UNzS2nDFYlUsQ=).

**Comment by hwittenborn** [comment]
That didn't show much that I didn't expect :P

Could you send over the output of the following commands?

```sh
type bash
trap true sigint
bash --version
lsb_release -cs
```

**Comment by oevcim** [comment]
![makedeb2](https://user-images.githubusercontent.com/61584685/144816861-febc0fa6-16a7-4e8f-96e0-b482babdb508.png)


hope turkish words are not make it confusing.

**Comment by oevcim** [comment]
I could manage to install up to 6.3.10-1 version successfully. But this version is also complaining about "option --install-layout not recognized".
hope this helps.

**Comment by hwittenborn** [comment]
I'll have to check out why that `trap` error's popping up, I'll do some more debugging sometime this week.

Regarding the `--install-layout` issue, are you passing any options to makedeb when you run that?

**Comment by oevcim** [comment]
No i am giving just "makedeb" command.
makedeb and makedeb-makepkg packages conflicting i think.

**Comment by hwittenborn** [comment]
@oevcim Does anything work now on the new releases of makedeb?

**Comment by hwittenborn** [comment]
Closing now due to no response. Feel free to send a message or open a new issue if you still experience problems.
