### ISSUE TITLE
Can't install makedeb from AUR

### ISSUE THREAD

**Issue by vifly** [hwittenborn/makedeb#66]
### Issue

[The latest commit on AUR](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=makedeb&id=918f763540008fda0b8abb90444c17eddd2d2e4b) caused failed to install makedeb, and the following pacman error message is:

```
loading package files...
checking for file conflicts...
error: failed to commit transaction (conflicting files)
makedeb: /etc/makepkg.conf exists in filesystem (owned by pacman)
makedeb: /usr/bin/makepkg-template exists in filesystem (owned by pacman)
Errors occurred, no packages were upgraded.
```

### Installation source

Arch User Repository (AUR)

### Installed release type

Stable

### Installed makedeb version

None

### Installed makepkg version

None

**Comment by hwittenborn** [comment]
I saw this issue yesterday in the makedeb Docker builds, I just haven't gotten the changes into beta or stable yet.

I literally just need to merge the changes into those branches, so it should be done quite shortly.
