### ISSUE TITLE
[AUR] Packages currently do not build properly

### ISSUE THREAD

**Issue by nightah** [hwittenborn/makedeb#7]
As it currently stands both the `makedeb` and `makedeb-alpha` packages expect `data.tar.xz` source however this does not exist within the specified `PKGBUILD` file.

Per the following feedback the below `PKGBUILD` will result in installable/buildable packages, however it also results in a non-workable version of `makedeb` with new errors:

```sh
# Author: Hunter Wittenborn <hunter@hunterwittenborn.com>
# Maintainer: Hunter Wittenborn <hunter@hunterwittenborn.com>

pkgname=makedeb-alpha
pkgver=2.11.2
pkgrel=1
pkgdesc="Create Debian archives from PKGBUILDs (alpha release)"
arch=('any')
depends=('pacman' 'dpkg')
license=('GPL3')
url="https://github.com/hwittenborn/makedeb"

source=("git+${url}")
sha256sums=('SKIP')

package() {
  # Normal setup - same as in Debian PKGBUILD
  mkdir -p "${pkgdir}/usr/bin/"
  
  cat "${srcdir}"/makedeb/src/functions/{*.sh,*/*.sh} >> "${pkgdir}/usr/bin/makedeb"
  
  cat "${srcdir}/makedeb/src/makedeb.sh" >> "${pkgdir}/usr/bin/makedeb"
  
  sed -i "s|DATABASE_DIR=.*|DATABASE_DIR=/usr/share/makedeb-db/|" "${pkgdir}/usr/bin/makedeb"

  # Disable auto install functionality as Arch doesn't use APT
  sed -i 's|${INSTALL}|INSTALL|' "${pkgdir}"/usr/bin/makedeb
  
  sed -i 's|INSTALL=.*|echo "APT is required for auto installation functionality, and has thus been disabled."; exit 1 ;;|' \
    "${pkgdir}/usr/bin/makedeb"
    
  sed -i 's|  echo "  -I,.*"||' "${pkgdir}/usr/bin/makedeb"
  
  sed -i 's|install_depends |true |g' "${pkgdir}/usr/bin/makedeb"
  sed -i 's|remove_depends |true |g' "${pkgdir}/usr/bin/makedeb"
}
```

_Originally posted by @hwittenborn in https://github.com/authelia/authelia/issues/573#issuecomment-862839783_

1. `/usr/bin/makedeb` does not have an executable bit (you can either fix this in your upstream repo or chmod in your PKGBUILD)
2.  The following block of code will result in an error `/usr/bin/makedeb: line 363: syntax error near unexpected token ;;'` when you try to run `makedeb`
```
 sed -i 's|INSTALL=.*|echo "APT is required for auto installation functionality, and has thus been disabled."; exit 1 ;;|' \
```

You need to drop the extra semicolon to become:
```
 sed -i 's|INSTALL=.*|echo "APT is required for auto installation functionality, and has thus been disabled."; exit 1 ;|' \
```

Once those issues have been resolved running `makedeb` results in the following message no matter what option is passed in:
```bash
mana ~ makedeb --help
APT is required for auto installation functionality, and has thus been disabled.
```

**Comment by hwittenborn** [comment]
@nightah I've added a variable that stops all APT functionality from working on the Arch release, and should fix all of the issues you mentioned (after I modify the PKGBUILD to fit the new release).

I'll (hopefully) be pushing the commits soon, I'm just waiting on finishing up some CI pipelines I use for deployments.

**Comment by hwittenborn** [comment]
@nightah I've pushed a new PKGBUILD to the AUR that should get everything working.

You'll need to get `makedeb-alpha` instead of `makedeb` until I get `makedeb`'s PKGBUILD updated, but I would recommend the alpha build anyway, as the stable branch lacks quite a few features atm.

If you're on Debian, there's also a repository you can use. Unless you're building from a prebuilt package, I'd probably use that to prevent any library issues.

If you want to go that route, there's a `makedeb-docs` repo on my profile that has instructions for setting up the Debian repository.

Feel free to reopen if you have any issues.

**Comment by hwittenborn** [comment]
Another update in case it helps:

I've published a Docker image (can be found in the README) that contains everything needed to build packages with makedeb.

I'm not sure how your CI pipelines are set up, but it might help with getting everything set up in them easier.
