### ISSUE TITLE
Dotfile found in package root

### ISSUE THREAD

**Issue by tdslot** [hwittenborn/makedeb#73]
## Environment 
On MacOS
```
brew install lima
limactl start default
```

Run build in container with lima:
```
nerdctl run --rm -it -v \
          (pwd)/debbuild:/results \
          --entrypoint bash ghcr.io/prebuiltmpr/mpr-builder:focal
```

Version:
```
builder@277920aa859f:/results$ makedeb --version
makedeb 8.5.9-1
Alpha Release
Installed from APT
```
## Problem
Can't not find dot files, but no dot files inside `$pkgdir`:
```
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/results/libmxf/pkg/libmxf/usr/lib/pkgconfig'
 /usr/bin/install -c -m 644 libMXF-1.0.pc '/results/libmxf/pkg/libmxf/usr/lib/pkgconfig'
make[3]: Leaving directory '/results/libmxf/src/libmxf'
make[2]: Leaving directory '/results/libmxf/src/libmxf'
make[1]: Leaving directory '/results/libmxf/src/libmxf'
[#] Tidying install...
  [->] Removing libtool files...
  [->] Purging unwanted files...
  [->] Removing static library files...
  [->] Stripping unneeded symbols from binaries and libraries...
  [->] Compressing man and info pages...
[#] Checking for packaging issues...
[!] Dotfile found in package root '/results/libmxf/pkg/libmxf/.*'
builder@277920aa859f:/results/libmxf$ ls -A
PKGBUILD  libmxf  pkg  src
builder@277920aa859f:/results/libmxf$ cd pkg/libmxf/
builder@277920aa859f:/results/libmxf/pkg/libmxf$ ls -A
usr
builder@277920aa859f:/results/libmxf/pkg/libmxf$
```

My `PKGBUILD` file:
```
# Maintainer: 

pkgname=libmxf
_commit=9b9860d
pkgver=1.0.4.$_commit
pkgrel=1
pkgdesc="libMXF is a low-level C library for reading and writing the SMPTE ST 377-1 MXF file format."
arch=('x86_64')
url="https://sourceforge.net/p/bmxlib/libmxf/ci/master/tree/"
license=('BSD 3-clause license')
makedepends=('uuid-dev' 'git' 'fakeroot' 'make' 'automake' 'autoconf' 'libtool' 'build-essential')
provides=('libmxf')
conflicts=('libmxf')
source=("git+https://git.code.sf.net/p/bmxlib/libmxf.git")
sha256sums=('SKIP')

prepare() {
    cd $pkgname
    git checkout $_commit
}

build() {
    cd $pkgname
    bash autogen.sh
    bash ./configure --prefix=/usr --disable-examples CFLAGS="-std=gnu99"
    make -j$(nproc)
}

package() {
    cd $pkgname
    make DESTDIR="$pkgdir" prefix="/usr" install
}


```

### Installation source

makedeb Package Repository (MPR)

### Installed release type

Alpha

### Installed makedeb version

makedeb 8.5.9-1 Alpha Release

### Installed makepkg version

makepkg-template (pacman) 6.0.0

**Comment by hwittenborn** [comment]
Does this still happen on the latest releases @tdslot?

**Comment by tdslot** [comment]
I tested with `podman` and `lima`. Yes it happen. But with `docker` no issue with that.

**Comment by hwittenborn** [comment]
Oh, it looks like it's considering `.*` to be a directory because it didn't find anything else. I have no clue why this is only happening in podman and lima, but I'll get a fix going shortly.

**Comment by hwittenborn** [comment]
Actually I'd like to test one more thing - Could you run `ls -a` from that directory you originally ran `ls -A` in your podman and lima containers so I can see what pops up?

**Comment by hwittenborn** [comment]
Closing since there hasn't been a response. Feel free to reopen if you're still having the issue.

**Comment by JehhB** [comment]
Hi, I am experiencing the same problem right now but it is happening for all packages for me.

For now I am aliasing `makedeb` to `LIBMAKEPKG_LINT_PACKAGE_DOTFILES_SH=0 makedeb`

but i think setting `nullglob` would be better so it still do check.

**Comment by Elsie19** [comment]
> Hi, I am experiencing the same problem right now but it is happening for all packages for me.
> 
> For now I am aliasing `makedeb` to `LIBMAKEPKG_LINT_PACKAGE_DOTFILES_SH=0 makedeb`
> 
> but i think setting `nullglob` would be better so it still do check.

Same issue here.
