### ISSUE TITLE
[AUR] Problems with the target architecture

### ISSUE THREAD

**Issue by RedErr404** [hwittenborn/makedeb#8]
When building a package, the first element of the enumeration of the arch=('x' 'y') parameter is used. If the target platform does not match, build problems appear.
makedeb version:
_Package: makedeb
Status: install ok installed
Maintainer: Hunter Wittenborn <git@hunterwittenborn.me>
Architecture: all
Source: makedeb.sh
Version: 2.0.6-1
Depends: makepkg, dpkg-dev, binutils, file
Conflicts: makedeb-alpha
Description: Make PKGBUILDs work on Debian-based distros (stable release)_

**Comment by hwittenborn** [comment]
This is probably just an issue I haven't gotten around to on the stable release.

The stable version is currently extremely behind on features, and there's not much I can do for the time being until I can get the alpha channel merged (Edit: just made a beta channel which should get things moving a bit quicker).

For the time being, you'll need to use the beta or alpha release. There's definitely more instability you'll get, but there's not many other options right now if you want most things to work.
