### ISSUE TITLE
Add `--no-color` option

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/makedeb#82]
### Description of feature

It would be nice to have a `--no-color` option so it's easier to parse the output of makedeb, such as when checking the output of makedeb in things such as unit testing scripts.

### Installed makedeb version

8.6.0-1

**Comment by Elsie19** [comment]
You can also check if a terminal supports colors at all with this:
```bash
tput colors
```
If the number is greater than 1, it's safe to assume it can use colors, but you can also test for if it can't with this:
```bash
tput -T dumb colors
```
Which will show `-1`, which means it "can't" support colors.

**Comment by hwittenborn** [comment]
I got 256 and -1 respectively going with your example:

![image](https://user-images.githubusercontent.com/74838472/147839533-42cfd480-01a3-424a-83fe-ff375f4a056f.png)

Though detecting if color should be used via that manner does sound safer than just checking if stderr is a terminal device (as seen in #81).
