### ISSUE TITLE
Add ability to handle `.deb` package sources automatically

### ISSUE THREAD

**Issue by zocker-160** [hwittenborn/makedeb#88]
### Description of feature

Currently packages that use official .deb files, need to unpack and move the files manually, which is exactly the same process each time and looks something like this:

```bash
package() {
    tar -xf 'data.tar.gz' -C "${pkgdir}"
    mkdir -p "${pkgdir}/DEBIAN"
    tar -xf 'control.tar.gz' -C "${pkgdir}/DEBIAN"
    rm "${pkgdir}/DEBIAN/control"
}
```
It would be very nice if this process could be automated by only having to specify the source file.

### Installed makedeb version

makedeb --version

**Comment by hwittenborn** [comment]
Superseded by #185.
