### ISSUE TITLE
FYI: https://github.com/prebuilder

### ISSUE THREAD

**Issue by KOLANICH** [hwittenborn/makedeb#9]
Hi. Excuse me for the disturbance, but you may be interested in https://github.com/prebuilder/prebuilder.py . It is a framework and a set of components for creating package building pipelines. Currently it got broken somewhere (and I have found no time to fix it yet) and has some issues unsolved (like making changes into `dpkg` its dependencies depend on, and the dependences themselves are not very finished), but the code is still present, and you may find it useful.

**Comment by hwittenborn** [comment]
Hi!

I'm a bit confused on what exactly it does still.

What exactly would this do inside of makedeb? Is there any specific parts you're thinking of?

**Comment by KOLANICH** [comment]
This is an another metabuild system, more high-level. But with a similar goal - get binary packages for software with the lowest resources (both in terms of human work and machine work) spent on my side (i.e. abusing CI services for that is OK) possible. It has an own python-based pipeline format, because repackaging often involves complex logic and bash is terrible error-prone choice for it. It is not fundamentally centered around Debian, it's just I use Ubuntu, so backends for Debian are the most developed.

So, likely nothing to do with makedeb itself, but more to do with DUR, I guess.
