### ISSUE TITLE
Add ability to handle `.AppImage` package sources automatically

### ISSUE THREAD

**Issue by zocker-160** [hwittenborn/makedeb#99]
### Description of feature

Very similar to #88 it would also be nice if makedeb would handle Appimages automatically and properly.

The main issue with Appimages currently is, that when launched directly, they potentially come with their own desktop integration and / or updater.
Both of which is not desirable, since updating and desktop integration should be handled by the deb file (and apt for that matter).

In order to solve this issue, there are two solutions I can think of right now:

- call the `.AppImage` with `env APPIMAGELAUNCHER_DISABLE=true`
  - only relevant when `appimagelauncher` is installed on the system
  - solves only the integration issue, not the updater issue
  - AppImage needs to get unpacked on each launch, which means slower startup
- unpack the AppImage using `./<packname>.AppImage --appimage-extract` into `/opt/<packagename>` for example
  - needs more testing, but I have not encountered issues with this approach so far

### Installed makedeb version

makedeb --version

**Comment by hwittenborn** [comment]
Superseded by #185.
